In [2]:
import pandas as pd
print(pd.__version__)

1.1.3


In [3]:
data = {
    "names":["길동","둘리","철수"],
    "age":[20,10,30],
    "addr":['서울','경기','부산']
}
#data
#DataFrame 객체 생성
data_df = pd.DataFrame(data)
print(type(data_df))
print(data_df.shape)
data_df#.head()

<class 'pandas.core.frame.DataFrame'>
(3, 3)


names  age addr
0    길동   20   서울
1    둘리   10   경기
2    철수   30   부산

In [5]:
import numpy as np

np.log2(8)

3.0

In [7]:
np.log2(20)

4.321928094887363

In [10]:
def add(n1, n2):
    return n1 + n2

In [12]:
add(10,20)

30

In [13]:
add2 = lambda n1, n2 : n1 + n2

In [14]:
add2(10,20)

30

In [17]:
data_df['age']

0    20
1    10
2    30
Name: age, dtype: int64

In [18]:
data_df['age'] = data_df['age'].map(lambda val: val * 10)

In [20]:
data_df['age']

0    200
1    100
2    300
Name: age, dtype: int64

In [21]:
data_df['log'] = data_df['age'].map(lambda val: np.log2(val))

In [22]:
data_df

names  age addr       log
0    길동  200   서울  7.643856
1    둘리  100   경기  6.643856
2    철수  300   부산  8.228819

In [6]:
for idx, row in data_df.iterrows():
    print(type(row))
    print(idx,row['addr'])

<class 'pandas.core.series.Series'>
0 서울
<class 'pandas.core.series.Series'>
1 경기
<class 'pandas.core.series.Series'>
2 부산


In [7]:
#names 컬럼의 데이터만 선택
data_df['names']

0    길동
1    둘리
2    철수
Name: names, dtype: object

In [8]:
#컬럼추가
data_df['phone'] = ['010-11-22','010-22-33','010-33-44']
data_df

names  age addr      phone
0    길동   20   서울  010-11-22
1    둘리   10   경기  010-22-33
2    철수   30   부산  010-33-44

In [9]:
print(len(data_df))
#seq컬럼 추가
data_df['seq'] = range(1,len(data_df)+1)
data_df

3


names  age addr      phone  seq
0    길동   20   서울  010-11-22    1
1    둘리   10   경기  010-22-33    2
2    철수   30   부산  010-33-44    3

In [13]:
#집계함수 사용
data_df

names  age addr      phone  seq
0    길동   20   서울  010-11-22    1
1    둘리   10   경기  010-22-33    2
2    철수   30   부산  010-33-44    3

In [14]:
data_df['성별'] = ['남','여','남']
data_df

names  age addr      phone  seq 성별
0    길동   20   서울  010-11-22    1  남
1    둘리   10   경기  010-22-33    2  여
2    철수   30   부산  010-33-44    3  남

In [15]:
#나이 최대값,최소,평균,중간
print('최대 ', data_df['age'].max())
print('최소 ',data_df['age'].min())
print('평균 ',data_df['age'].mean())
print('중간 ',data_df['age'].median())
print('카운트 ',data_df['age'].count())
print('합계 ',data_df['age'].sum())

최대  30
최소  10
평균  20.0
중간  20.0
카운트  3
합계  60


In [16]:
data_df.describe()

age  seq
count   3.0  3.0
mean   20.0  2.0
std    10.0  1.0
min    10.0  1.0
25%    15.0  1.5
50%    20.0  2.0
75%    25.0  2.5
max    30.0  3.0

In [17]:
data_df['age'].describe()

count     3.0
mean     20.0
std      10.0
min      10.0
25%      15.0
50%      20.0
75%      25.0
max      30.0
Name: age, dtype: float64

In [10]:
data_df.tail(2)

names  age addr      phone  seq 성별
1    둘리   10   경기  010-22-33    2  여
2    철수   30   부산  010-33-44    3  남

In [18]:
print('몇행 몇열 ' , data_df.shape)
print('컬럼명 ', data_df.columns)
print('인덱스 ', data_df.index)
print('값들 ', data_df.values,  type(data_df.values))


몇행 몇열  (3, 6)
컬럼명  Index(['names', 'age', 'addr', 'phone', 'seq', '성별'], dtype='object')
인덱스  RangeIndex(start=0, stop=3, step=1)
값들  [['길동' 20 '서울' '010-11-22' 1 '남']
 ['둘리' 10 '경기' '010-22-33' 2 '여']
 ['철수' 30 '부산' '010-33-44' 3 '남']] <class 'numpy.ndarray'>


In [12]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   names   3 non-null      object
 1   age     3 non-null      int64 
 2   addr    3 non-null      object
 3   phone   3 non-null      object
 4   seq     3 non-null      int32 
 5   성별      3 non-null      object
dtypes: int32(1), int64(1), object(4)
memory usage: 260.0+ bytes


In [13]:
data_df.head()

names  age addr      phone  seq 성별
0    길동   20   서울  010-11-22    1  남
1    둘리   10   경기  010-22-33    2  여
2    철수   30   부산  010-33-44    3  남

In [14]:
#names 컬럼의 값들을 선택해라  select names from table명 
#한개의 열(컬럼)을 선택
print(type(data_df['names']))
data_df['names']

<class 'pandas.core.series.Series'>


0    길동
1    둘리
2    철수
Name: names, dtype: object

In [15]:
#한개의 행(로우)을 선택
print(type(data_df.loc[0]))
data_df.loc[0]

<class 'pandas.core.series.Series'>


names           길동
age             20
addr            서울
phone    010-11-22
seq              1
성별               남
Name: 0, dtype: object

In [16]:
#Series 객체생성
series1 = pd.Series([10,20,30])
series1

0    10
1    20
2    30
dtype: int64

In [17]:
series2 = pd.Series( {'title':'Dynamite','가수':'방탄'})
series2

title    Dynamite
가수             방탄
dtype: object

In [18]:
song_list = [
    {'title':'Dynamite','가수':'방탄'},
    {'title':'Girl','가수':'블랙핑크'}
]

#비어 있는 DataFrame 객체
data_df = pd.DataFrame(columns=['title','가수'])
data_df

Empty DataFrame
Columns: [title, 가수]
Index: []

In [19]:
for song in song_list:
    #Series 객체 생성
    series_obj = pd.Series(song)
    #Series 객체를 DataFrame 객체에 추가한다
    data_df = data_df.append(series_obj, ignore_index=True)

data_df    

title    가수
0  Dynamite    방탄
1      Girl  블랙핑크

### numpy 사용

In [3]:
import numpy as np

In [4]:
alpha_list = [0.001, 0.01, 0.1, 1, 10, 100]
np.log10(alpha_list)

array([-3., -2., -1.,  0.,  1.,  2.])

In [31]:
data = [10, 'aa']
arr = np.array(data)
print(arr.dtype)
arr

<U11


array(['10', 'aa'], dtype='<U11')

In [20]:
data1 = [6,7.5,9,0,1]
arr1 = np.array(data1)
print(arr1.shape)
print(arr1.dtype)
print(type(arr1))
arr1

(5,)
float64
<class 'numpy.ndarray'>


array([6. , 7.5, 9. , 0. , 1. ])

In [21]:
data2 = [[1,2,3,4],
        [5,6,7,8]]
arr2 = np.array(data2)
print(arr2.shape)
print(arr2.dtype)
#arr2 = np.array(data2)
arr2

(2, 4)
int32


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### sum() 함수

In [41]:
print(arr2.sum())
#컬럼별로 sum, 각 열에 대한 합을 연산
print(arr2.sum(axis=0))

#로우별로 sum, 각 행에 대한 합을 연산
print(arr2.sum(axis=1))

36
[ 6  8 10 12]
[10 26]


#### arange() 함수

In [24]:
np.arange(1,10+1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
for val in np.arange(1,10+1):
    print(val)

1
2
3
4
5
6
7
8
9
10


#### reshape

In [27]:
arr = np.arange(12)
print(arr)
sap = arr.reshape(3, 4)
print(sap.shape)
sap

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
sap.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])


- 총 12개의 원소가 들어있는 배열 x에 대해서 x.reshape(-1, 정수) 를 해주면 
- '열(column)' 차원의 '정수'에 따라서 12개의 원소가 빠짐없이 배치될 수 있도록 '-1'이 들어가 있는 '행(row)'의 
- 개수가 가변적으로 정해짐을 알 수 있습니다.  

* 즉, 행이나 열의 특정 차원을 기준으로 재배열하고 싶은 행이나 열의 개수가 있으면 나머지 차원의 개수는 '-1'로 해두면 알아서 자동으로 재배열을 해주니 편리한 기능




In [60]:
# sap.reshape(12, 1)
arr.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [61]:
# sap.reshape(6, 2)
arr.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [64]:
# sap.reshape(4, 3)
arr.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
arr2 = np.arange(12)
sap2 = arr2.reshape(2, -1)
sap2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [68]:
sap2 = arr2.reshape(3, -1)
sap2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### column_stack

In [2]:
import numpy as np
# [1,2,3]과 [4,5,6] 두 리스트를 일렬로 세운 다음 나란히 옆으로 붙임
np.column_stack(([1,2,3],[4,5,6]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})


In [23]:
df1

lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5

In [24]:
df2

rkey  value
0  foo      5
1  bar      6
2  baz      7
3  foo      8

In [25]:
df3 = df2.set_index('rkey')
df3

value
rkey       
foo       5
bar       6
baz       7
foo       8

In [26]:
df1.merge(df2, left_on='lkey', right_on='rkey')

lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

In [27]:
df1.merge(df3,left_on='lkey', right_on=df3.index, how='left')

lkey  value_x  value_y
0  foo        1        5
1  foo        1        8
2  bar        2        6
3  baz        3        7
4  foo        5        5
5  foo        5        8